version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/code

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devdb

  adminer:
    image: adminer
    ports:
      - 8080:8080
